apiVersion: v1
kind: Service
metadata:
  name: es-sync
  labels:
    name: es-sync
spec:
  type: NodePort
  ports:
    - nodePort: 31780
      port: 8272
      protocol: TCP
  selector:
    name: es-sync
