apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microsvc.name}}-{{ .Values.microsvc.env }} 
  labels:
    name: {{ .Values.microsvc.name}}-{{ .Values.microsvc.env }}
spec:
  type: ClusterIP
  ports:
    - port: 8272
      targetPort: 80
      protocol: TCP
  selector:
    name: {{ .Values.microsvc.name}}-{{ .Values.microsvc.env }}
