apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.environment }}-mbe
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.namespace }}
    name: {{ .Values.cluster }}
  project: {{ .Values.environment }}-project
  source:
    path: {{ .Values.path }}
    repoURL: {{ .Values.gitrepo }}
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true