apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mbe-{{ .Values.environment }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: {{ .Values.cluster }}
  project: {{ .Values.environment }}-project
  source:
    path: {{ .Values.path }}
    repoURL: {{ .Values.gitrepo }}
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true