apiVersion: v1
kind: Service
metadata:
  name: micro-ui
  labels:
    name: micro-ui
spec:
  type: NodePort
  ports:
    - nodePort: 31780
      port: 8272
      protocol: TCP
  selector:
    name: micro-ui
