apiVersion: v1
data:
  myvalue: mykey
  secondvalue: secondkey
  thisdkey: thisdvalue
  fourth: four
  fifth: five
  sixth: six
  seventh: seven
  eigth: eight
  ninth: nine
  tenth: te
kind: ConfigMap
metadata:
  name: forg2
