apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
data:
  key: "value"
  key1: value1
  key2: value2

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Values.appName }}-service
# spec:
#   selector:
#     app: {{ .Values.appName }}
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: {{ .Values.appName }}-deployment
# spec:
#   selector:
#     matchLabels:
#       app: {{ .Values.appName }}
#   template:
#     metadata:
#       labels:
#         app: {{ .Values.appName }}
#     spec:
#       containers:
#         - name: {{ .Values.appName }}-container
#           image: nginx:latest
#           ports:
#             - containerPort: 80
