apiVersion: v1
kind: Service
metadata:
  name: external
  labels:
    name: external
spec:
  type: NodePort
  ports:
    - nodePort: 31780
      port: 8272
      protocol: TCP
  selector:
    name: external
