image:
  #change repository
  repository: us.gcr.io/blume-shared-container-images/analytics-ui
  tag: donotchange

service:
  type: NodePort
ingress:
  enabled: false
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
resources: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

