apiVersion: v2
name: newapp-prod
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: micro-ui
    version: 0.1.0
    repository: file://../../newapp/micro-ui/chart/prod
  - name: app
    version: 0.1.0
    repository: file://../../newapp/app/chart/prod
  - name: external
    version: 0.1.0
    repository: file://../../newapp/external/chart/prod
  - name: es-sync
    version: 0.1.0
    repository: file://../../newapp/es-sync/chart/prod
