apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: app
=======
  name: appdemo
>>>>>>> a2a19654e84eab310a87994dc2b7bfa63afb0d56
  labels:
    name: app
spec:
  type: ClusterIP
  ports:
    - port: 8272
      targetPort: 80
      protocol: TCP
  selector:
    name: app
