apiVersion: apps/v1
kind: Deployment
metadata:
  annotation:
    argocd.argoproj.io/sync-wave: "-2"        
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        env:
        - name: PMA_HOST
          value: mysql
        ports:
        - containerPort: 80
