apiVersion: v1
kind: Service
metadata:
  name: demoapp
  labels:
    name: demoapp
spec:
  type: ClusterIP
  ports:
    - port: 8272
      targetPort: 80
      protocol: TCP
  selector:
    name: demoapp
