apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: es-sync
=======
  name: es-sync-demo
>>>>>>> a2a19654e84eab310a87994dc2b7bfa63afb0d56
  labels:
    name: es-sync
spec:
  type: ClusterIP
  ports:
    - port: 8272
      targetPort: 80
      protocol: TCP
  selector:
    name: es-sync
